### ISSUE TITLE
no /dev/isgx after installing driver

### ISSUE THREAD

**Issue by pblin** [01org/linux-sgx-driver#68]
Follow the installation instruction in READM of this repo. 
Azure VM, OS: Ubuntu 16.04
No /dev/isgx after installation, but /dev/sgx exists. the problem persists after restarting VM. 

compiled and ran https://github.com/ayeks/SGX-hardware/blob/master/test-sgx.c , the result shows that SGX is available and supported.

**Comment by pblin** [comment]
The problem was resolved only after upgrading OS to Ubuntu 18.04.

**Comment by piotr-roslaniec** [comment]
I also faced this issue on Azure Confidential Computing VM (Standard_DC2s). 
It was resolved by upgrade to 18.04 suggested by @pblin 

```
$  lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
$ uname -r 
4.15.0-1036-azure
```

// Edit:
I also managed to install drivers on Ubuntu 16.04 LTS: make sure you disable inclusion of Open Enclave SDK during VM creation:
![image](https://user-images.githubusercontent.com/39299780/52796388-02091500-3074-11e9-8666-9d190929e078.png)

**Comment by stefandeml** [comment]
I'm still facing the issue under Ubuntu 18.04:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```
I have neither /dev/sgx nor dev/isgx available on my machine. 
The aesmd service works, as do the SampleCodes.

Any idea how to debug this?

**Comment by clefru** [comment]
In this git repo run: 
```
make install
depmod -a
```
https://github.com/intel/linux-sgx-driver/pull/75 adds the depmod step to make install.

Edit: I am not sure, why the depmod step is necessary under Ubuntu, the kernel does a DEPMOD step itself when installing modules. Fact is, "modprobe isgx" doesn't work for me without a manual "depmod -a" first.

**Comment by stefandeml** [comment]
Thanks for the support.
Unfortunately this fix didn't help on my end. Still missing `/dev/isgx`

**Comment by sergeay** [comment]
What is the output of dmesg | grep sgx?

**Comment by stefandeml** [comment]
Can be closed. I had a BIOS reset and SGX has been disabled .

**Comment by danintel** [comment]
BTW, I have `/dev/sgx` on Microsoft Asure through Azure Confidential Compute running Ubuntu 18, but **no** `/dev/isgx` .

Update: `/dev/isgx` and `/dev/sgx` are **not** compatible. Here's the answer I got:

> No, /dev/sgx (regular Intel SGX driver) and /dev/isgx (DCAP driver) are not interchangeable…  one takes an EINITTOKEN and the other doesn’t.  And the AESM isn’t usually started in the Azure VMs on the initial installation since OE does not use it.  Try manually starting the AESM.

The `/dev/sgx` driver (kernel module `intel_sgx`) is for DCAP-enabled systems (with your own authentication service).

The `/dev/isgx` driver (kernel module `isgx`) is for non-DCAP systems (which uses Intel Authentication Service, IAS).

If you want to switch from one to the other, make sure you run the `uninstall.sh` script before even thinking of unzipping/untaring the new driver files (or it will be overwritten):

`sudo /opt/intel/sgxdriver/uninstall.sh` # The path to `uninstall.sh` may differ for your system.

If the uninstall.sh script is missing, uninstall as follows:
```
sudo service aesmd stop
sudo rm -f $(find /lib/modules -name intel_sgx.ko)
sudo /sbin/depmod
sudo sed -i '/^intel_sgx$/d' /etc/modules
sudo rm -f /etc/sysconfig/modules/intel_sgx.modules
sudo rm -f /etc/modules-load.d/intel_sgx.conf
```

BTW,  aesmd was started for me (use `systemctl status aesmd`), but still no `/dev/isgx`, even on Ubuntu 18 (Bionic)

P.P.S., you can determine if you have Intel SGX (whether or not it is BIOS enabled) with: `cpuid |grep SGX` on Linux (you may need to install package `cpuid`)

P.P.P.S., if you get a `SGX is not enabled` message in `/var/log/syslog`, enable SGX in the BIOS (F2 or ESC or ....)

I wrote an Intel SGX cheat sheet here that includes the above:
https://software.intel.com/en-us/forums/intel-software-guard-extensions-intel-sgx/topic/848808
